# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build -i -s
      
    - name: Prepare publications
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_RINGFILE: ${{ secrets.GPG_RINGFILE }}
      run: |
        sudo bash -c "echo 'signing.keyId=$GPG_KEY_ID >> gradle.properties"
        sudo bash -c "echo 'signing.password=$GPG_PASSWORD >> gradle.properties"
        sudo bash -c "echo 'signing.secretKeyRingFile=$GPG_RINGFILE >> gradle.properties"

    - name: Publish to GitHub Packages
      run: gradle publish -PapiKey=${{ secrets.SONOTYPE_TOKEN }}
