# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.3.0
      with:
        distribution: 'adopt-hotspot'
        java-version: 11

    - uses: actions/cache@v2.1.6
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle [Macos]
      uses: eskatos/gradle-command-action@v1
      if: ${{ startsWith(matrix.os, 'macos') }}
      with:
        arguments: clean build -x :jsNodeTest -i -s

    - name: Build with Gradle [Windows]
      uses: eskatos/gradle-command-action@v1
      if: ${{ startsWith(matrix.os, 'macos') }}
      with:
        arguments: clean build -x :jsNodeTest -x compilePosix -i -s
      
    - name: Prepare publications posix
      if: ${{ startsWith(matrix.os, 'macos') }}
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_RINGFILE: ${{ secrets.GPG_RINGFILE }}
        GPG_SECRET_CONTENT: ${{ secrets.GPG_KEY_CONTENTS }}
      run: |
        sudo bash -c "echo '$GPG_SECRET_CONTENT' | base64 -d > '$GPG_RINGFILE'"
        bash -c "echo 'signing.keyId=$GPG_KEY_ID' >> gradle.properties"
        bash -c "echo 'signing.password=$GPG_PASSWORD' >> gradle.properties"
        bash -c "echo 'signing.secretKeyRingFile=$GPG_RINGFILE' >> gradle.properties"
        
    - name: Prepare publications mingw
      if: ${{ startsWith(matrix.os, 'windows') }}
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        GPG_RINGFILE: ${{ secrets.GPG_RINGFILE }}
        GPG_SECRET_CONTENT: ${{ secrets.GPG_KEY_CONTENTS }}
      run: |
        $Env:GPG_SECRET_CONTENT | Out-File encodedContent.ring
        certutil -decode encodedContent.ring $Env:GPG_RINGFILE
        echo signing.keyId=$Env:GPG_KEY_ID >> gradle.properties
        echo signing.password=$Env:GPG_PASSWORD >> gradle.properties
        echo signing.secretKeyRingFile=$Env:GPG_RINGFILE >> gradle.properties

    - uses: eskatos/gradle-command-action@v1
      name: Publish targets to maven
      with:
        arguments: publish -d -s -PapiKey=${{ secrets.SONOTYPE_TOKEN }} '-Dorg.gradle.jvmargs=-Xmx2g -XX:-UseGCOverheadLimit -Dfile.encoding=UTF-8'
      if: ${{ startsWith(matrix.os, 'macos') && runner.arch == 'ARM64' }}

    - uses: eskatos/gradle-command-action@v1
      name: Publish targets to maven
      with:
        arguments: publishMingwX64PublicationToMavenRepository -s -d -x compilePosix -PapiKey=${{ secrets.SONOTYPE_TOKEN }} '-Dorg.gradle.jvmargs=-Xmx2g -XX:-UseGCOverheadLimit -Dfile.encoding=UTF-8'
      if: ${{ startsWith(matrix.os, 'windows') }}
